### ISSUE TITLE
Support for Feather V2

### ISSUE THREAD

**Issue by ddelange** [coady/graphique#18]
Hi :wave:

Would it make sense to support [Feather V2](https://arrow.apache.org/docs/python/feather.html#)?

Mainly for even faster reads, here's a [benchmark](https://ursalabs.org/blog/2020-feather-v2/).

**Comment by coady** [comment]
Like #18, any table is supported via a [custom app](https://github.com/coady/graphique/blob/main/README.md#configuration).
```python
import pyarrow.feather as feather
from graphique import GraphQL

app = GraphQL(feather.read_table(...))
```

**Comment by ddelange** [comment]
thanks for the responses!
