### ISSUE TITLE
Support for S3

### ISSUE THREAD

**Issue by ddelange** [coady/graphique#19]
Hi :wave:

Do you think it makes sense to add support for `s3://` input URI (single file or directory)?

The native [implementation](https://arrow.apache.org/docs/python/filesystems.html#s3) from arrow should allow for faster (lazy) startup times of new replicas if I'm not mistaken.

**Comment by ddelange** [comment]
there are a bunch of other filesystems that could be supported using the `ds.dataset(..., filesystem=fs)` mechanic ref https://arrow.apache.org/docs/python/filesystems.html#using-fsspec-compatible-filesystems-with-arrow

**Comment by ddelange** [comment]
It looks like filesystem is already inferred from the input URI [ref](https://arrow.apache.org/docs/python/filesystems.html#reading-and-writing-files), so then what about the isdir check you do for hive partitioning? Can that also be inferred? :thinking:

**Comment by coady** [comment]
Other filesystems are supported, by using a [custom app](https://github.com/coady/graphique/blob/main/README.md#configuration).
```python
import pyarrow.dataset as ds
from graphique import GraphQL

app = GraphQL(ds.dataset(...))
```

**Comment by ddelange** [comment]
awesome:)
